### ISSUE TITLE
Massively reduce API

### ISSUE THREAD

**Issue by mgold** [elm-community/elm-random-extra#2]
The original library was written by an individual who tried to come up with as many might-possibly-be-useful functions without considering that a huge API makes it harder to find useful functions and harder to maintain. Also, a lot of the submodules have fallen out of core in 0.17. So here are some API design principles:
- Never duplicate something in core.
- Build generators, not functions that handle seeds.
- One-liners usually aren't worth the effort. Except for really common patterns or error-prone cases, let the end user figure out how to put the pieces together.
  - Corollary: exported functions should do useful work.
- Write what is useful, not what is possible.
- Function names should be consistent with core.
- Comprehensible beats comprehensive.
- Poor documentation is a bug.

You can follow my progress in the `upgrade-0.17` branch.

**Comment by eeue56** [comment]
@mgold, this needs to be published sooner rather than later. It's a blocker for elm-check, which is a blocker for a lot of projects. This issue is a worthy goal - but it's far more important to us to be able to not block other packages upgrading.

**Comment by mgold** [comment]
Got it. I'll try to get this out in the next few hours.

**Comment by mgold** [comment]
Done on new fork.
